---
- name: install php70
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - rh-php70
    - rh-php70-php-cli
    - rh-php70-php-common
    - rh-php70-php-devel
    - rh-php70-php-gd
    - rh-php70-php-fpm
    - rh-php70-php-mbstring
    - rh-php70-php-json
    - rh-php70-php-mysqlnd
    - rh-php70-php-opcache
    - rh-php70-php-pdo
    - rh-php70-php-pear
    - rh-php70-php-xml

- name: enable rh-php70-php-fpm
  service:
    name: rh-php70-php-fpm
    state: started
    enabled: yes

- name: put php.ini
  template:
    src: php.ini
    dest: /etc/opt/rh/rh-php70/php.ini

- name: put php.ini
  template:
    src: php-fpm.d/www.conf
    dest: /etc/opt/rh/rh-php70/php-fpm.d/www.conf
  notify: restart php-fpm