---
- name: rbenv
  git: repo=https://github.com/rbenv/rbenv.git dest={{ rbenv_root }} clone=yes
- name: ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build clone=yes
- name: rbenv.sh
  template: src=profile.d/rbenv.sh dest=/etc/profile.d/
- name: rbenv installed?
  shell: ls {{ rbenv_root }}/versions/{{ ruby_version }} && echo 1 || echo 0
  register: rbenv_is_installed
- name: install ruby
  shell: source /etc/profile.d/rbenv.sh; rbenv install {{ ruby_version }}
  when: rbenv_is_installed == 0
- name: rehash
  shell: source /etc/profile.d/rbenv.sh; rbenv rehash
- name: rbenv global
  shell: source /etc/profile.d/rbenv.sh; rbenv global {{ ruby_version }}
- name: install bundler
  shell: source /etc/profile.d/rbenv.sh; gem install bundler -v {{ bundler_version }}
- name: rehash
  shell: source /etc/profile.d/rbenv.sh; rbenv rehash
- name: puma init script
  template: src=init.d/puma dest=/etc/init.d/
- name: puma chmod
  file: path=/etc/init.d/puma state=touch mode=0755 owner=ec2-user group=ec2-user
- name: add chkconfig
  shell: chkconfig --add puma
- name: chkconfig on
  shell: chkconfig puma on
- name: rails_key.sh
  template: src=profile.d/rails_key.sh dest=/etc/profile.d/
- name: mkdir,chown,chmod to /var/www/{{ app_name }}
  file: path=/var/www/{{ app_name }} state=directory mode=0755 group=ec2-user owner=ec2-user
