---
- name: put nginx.yum.conf
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: 
    name: "{{ item }}"
  with_items:
    - nginx

- name: enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: create document_root
  file:
    path: "/var/www/{{ server_name }}"
    state: directory
    owner: nginx
    group: nginx
    mode: "g+w,g+s"

- name: put nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: put /etc/nginx/conf.d/default.conf
  template:
    src: conf.d/default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx 
