---
- name: epel
  yum: name=epel-release state=latest
- name: yum update
  yum: name=* state=latest
- name: yum install
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - autoconf
    - automake
    - bison-devel
    - byacc
    - bzip2
    - bzip2-devel
    - curl-devel
    - gcc
    - gcc-c++
    - git
    - libffi-devel
    - libxml2-devel
    - libxslt-devel
    - libyaml-devel
    - libjpeg-devel
    - libpng-devel
    - make
    - nodejs
    - npm
    - openssl-devel
    - patch
    - postfix
    - readline-devel
    - sqlite-devel
    - sudo
    - tar
    - unzip
    - v8-devel
    - zip
    - zlib-devel
    - ImageMagick-devel
- name: switch mta
  shell: alternatives --set mta /usr/sbin/sendmail.postfix
- name: stop sendmail
  service: name=sendmail state=stopped enabled=no
- name: service postfix ntpd ntpdate
  service: name={{ item }} state=started enabled=yes
  with_items:
    - postfix
    - ntpd
    - ntpdate
- name: /etc/sysconfig/clock
  template: src=clock dest=/etc/sysconfig/
- name: localtime
  shell: rm /etc/localtime; ln -sf /usr/share/zoneinfo/{{ timezone }} /etc/localtime
- name: logrotate
  template: src=logrotate.conf dest=/etc/
- name: logrotate rails_app
  template: src=logrotate.d/rails_app dest=/etc/logrotate.d/{{ app_name }}
