---
- name: install httpd
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - httpd24
    - httpd24-tools
    - mod24_ssl

- name: put logrotate.d/httpd
  template:
    src: logrotate.d/httpd
    dest: /etc/logrotate.d/httpd

- name: create document root
  file: 
    path: /var/www/{{ server_name }}
    state: directory
    owner: root
    group: apache
    mode: 0775

- name: chmod g+s document root
  file:
    path: /var/www/{{ server_name }}
    state: directory
    mode: "g+s"

- name: put conf.modules.d/*.conf
  template:
    src: conf.modules.d/{{ item }}
    dest: /etc/httpd/conf.modules.d/{{ item }}
  with_items:
    - 00-base.conf
    - 00-mpm.conf
    - 00-proxy.conf

- name: put httpd.conf
  template: 
    src: conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: put conf.d/*.conf
  template:
    src: conf.d/{{ item }}
    dest: /etc/httpd/conf.d/{{ item }}
  with_items:
    - autoindex.conf
    - default.conf
    - deflate.conf
    - htpasswd.conf

- name: put conf.d/mpm.conf
  template:
    src: conf.d/mpm-{{ instance }}.conf
    dest: /etc/httpd/conf.d/mpm.conf

- name: create ssl files dir
  file:
    path: /etc/httpd/conf/ssl/
    state: directory
  when: use_ssl

- name: put ssl files
  copy:
    src: ssl/{{ item }}
    dest: /etc/httpd/conf/ssl/{{ item }}
  with_items:
    - server.key
    - server.pem
    - server-ca.pem
  when: use_ssl

- name: put conf.d/ssl.conf
  template:
    src: conf.d/ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
  when: use_ssl

- name: run httpd
  service: 
    name: httpd
    state: started
    enabled: yes

- name: usermod ec2-user
  user:
    name: ec2-user
    groups: apache
    append: yes
