---
- name: install httpd
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - httpd24
    - httpd24-tools
    - mod24_ssl

- name: create document root
  file: 
    path: /var/www/{{ server_name }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: run httpd
  service: 
    name: httpd
    state: started
    enabled: yes

- name: put conf.modules.d/*.conf
  template:
    src: conf.modules.d/{{ item }}
    dest: /etc/httpd/conf.modules.d/{{ item }}
  with_items:
    - 00-base.conf
    - 00-mpm.conf
    - 00-proxy.conf

- name: put httpd.conf
  template: 
    src: conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify: reload httpd

- name: put conf.d/*.conf
  template:
    src: conf.d/{{ item }}
    dest: /etc/httpd/conf.d/{{ item }}
  with_items:
    - autoindex.conf
    - default.conf
    - deflate.conf
    - htpasswd.conf
    - mpm.conf
  notify: reload httpd

- name: put logrotate.d/httpd
  template:
    src: logrotate.d/httpd
    dest: /etc/logrotate.d/httpd