---
- name: put mariadb.repo
  copy:
    src: mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo

- name: install MariaDB-server
  yum:
    name: "{{ item }}"
  with_items:
    - MariaDB-client
    - MariaDB-server

- name: enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
