---
- name: install nginx
  yum: name=nginx state=latest
- name: service nginx
  service: name=nginx state=started enabled=yes
- name: nginx.conf
  template: src=nginx.conf dest=/etc/nginx/
- name: nginx/conf.d/production.conf
  template: src=conf.d/production.conf dest=/etc/nginx/conf.d/
- name: nginx/ssl
  file: path=/etc/nginx/ssl state=directory mode=0640 owner=nginx group=nginx
